encoding: utf-8
highlighter: rouge
paginate: 5
paginate_path: "index/page:num"
excerpt_separator: "<!--more-->"

# Serving
host : 0.0.0.0
port : 4000
url: http://localhost:4000
baseurl : /

gems: [jekyll-paginate]