encoding: utf-8
highlighter: rouge
paginate: 5
paginate_path: "blog/page:num"
excerpt_separator: "<!---\n<!–end_preview–>\n-->"

# Serving
host : 0.0.0.0
port : 4000
url: http://localhost:4000
baseurl : /